insert into credenziali (id, username, password, ruolo) values(nextval('credenziali_seq'), 'paolo', '$2a$10$yWAIDyuEr78BBBFZ5cYh8.Nw4gUHFTRG5FwaWqNCGeOD8M4mh3.xy', 'ADMIN');
INSERT INTO area (id, nome, capacita, descrizione, immagine_url) VALUES (nextval('area_seq'), 'Zona Cani Grandi', 15, 'Area verde spaziosa dedicata al recupero e allo sgambamento dei cani di taglia grande.', '/immagini/area_cani.png');
INSERT INTO area (id, nome, capacita, descrizione, immagine_url) VALUES (nextval('area_seq'), 'Gattile Interno', 20, 'Struttura coperta e riscaldata con tiragraffi e cucce per il soggiorno dei gatti.', '/immagini/area_gatti.png');
INSERT INTO volontario (id, nome, cognome, codice_fiscale, specializzazione, data_di_nascita, immagine_url) VALUES (nextval('volontario_seq'), 'Marco', 'Rossi', 'RSSMRC80A01H501W', 'Cani di taglia grande e rieducazione', '1980-01-01', '/immagini/marco_rossi.png');
INSERT INTO volontario (id, nome, cognome, codice_fiscale, specializzazione, data_di_nascita, immagine_url) VALUES (nextval('volontario_seq'), 'Laura', 'Bianchi', 'BNCHLR92M41H501X', 'Gatti anziani e terapie mediche', '1992-08-21', '/immagini/laura_bianchi.png');
INSERT INTO cartella_clinica (id, data_visita, diagnosi, terapia, peso) VALUES (nextval('cartella_clinica_seq'), '2026-05-10', 'In salute, leggera dermatite da stress.', 'Applicazione lozione lenitiva una volta al giorno per 7 giorni.', 32.5);
INSERT INTO cartella_clinica (id, data_visita, diagnosi, terapia, peso) VALUES (nextval('cartella_clinica_seq'), '2026-05-15', 'Controllo di routine, ottimale stato nutrizionale.', 'Nessuna terapia necessaria, consigliati croccantini sterilizzati.', 4.2);
INSERT INTO animale (id, nome, specie, razza, data_nascita, data_arrivo, descrizione, area_id, volontario_id, cartella_clinica_id, immagine_url) VALUES (nextval('animale_seq'), 'Rocky', 'CANE', 'Pastore Tedesco', '2022-03-15', '2026-01-10', 'Un cane molto affettuoso, giocherellone e obbediente.', 1, 1, 1, '/immagini/rocky.jpg');
INSERT INTO animale (id, nome, specie, razza, data_nascita, data_arrivo, descrizione, area_id, volontario_id, cartella_clinica_id, immagine_url) VALUES (nextval('animale_seq'), 'Luna', 'GATTO', 'Siamese', '2024-06-20', '2026-05-02', 'Gattina tranquilla che ama le coccole e i sonnellini al sole.', 51, 51, 51, '/immagini/luna.png');
